### ISSUE TITLE
Create sections for graphs

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-book#196]
We have mentions of various graph commands across different parts of the book. I think it is better to group them into the separate section, after "Analysis" one. Since analysis was introduced already, explaining and showing all graph features will be easier, and more visual.

See:
- https://github.com/radare/radare2book/issues/163
- https://radare.gitbooks.io/radare2book/content/analysis/graphs.html

**Comment by trufae** [comment]
also done
