### ISSUE TITLE
Remove/split "Crackmes" into the separate Tutorial.

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-book#199]
It doesn't really belong to this reference manual, and should be updated, and become a good tutorial of its own. Preferably with references to the radare2 book chapters where applicable. Some information should be added in the radare2 book too.

**Comment by trufae** [comment]
its already in a separate chapter, but all this requires proper rewording, well the whole thing, so closing this ticket as its not proposing anything not done
