### ISSUE TITLE
Document ragg2 and `g` commands

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-book#216]
Basics on how to use it, simple and C syntax, couple examples

**Comment by kuqadk3** [comment]
Sorry, but I couldn't find any 'g' command in ragg2.c source code

https://github.com/radareorg/radare2/blob/master/libr/main/ragg2.c

**Comment by XVilka** [comment]
@kuqadk3 what I meant is the `g` command in the radare2 itself, it's the command that exposes ragg2 features but inside the radare2 session.

**Comment by trufae** [comment]
initial stuff is there, updated recently
