### ISSUE TITLE
[FR] other e-book formats

### ISSUE THREAD

**Issue by ildar** [radareorg/radare2-book#280]
epub/fb2 are very desirable for self-education. PDF is also demanded mostly.

**Comment by Maijin** [comment]
You can do epub and PDF by running npm epub already

**Comment by ildar** [comment]
I can do it. but still think it's a good idea to give noobs a link

**Comment by ildar** [comment]
As an example on how I'd like a ebook to look like.
https://flibusta.is/b/619884/

**Comment by ildar** [comment]
That's fair.
Could anyone please share a link to a ready-built epub? as I wrote:
> but still think it's a good idea to give noobs a link
... including right in the book itself.
Please?

**Comment by trufae** [comment]
Its in the first link if you google for r2book or see the radare website

https://radare.gitbooks.io/radare2book/content/

**Comment by ildar** [comment]
Oh!
I'm sorry, but we have a messy mess here:
1. https://github.com/radareorg/radare2book has two links to
http://book.rada.re/ ,
2. which is the outdated version of the book and should be changed to
redirect to the current version or terminated;
3. all the gitbook links are broken.

**Comment by trufae** [comment]
Yes, I just realized that xvilka removed the gitbook account associated to this repository when they forked r2.. >_< .. well now I can setup things in github ci without depending on anyone or any external service or privative tooling. So this issue wont happen again.

I just integrated pandoc into the CI pipeline to generate the PDF file in there. it's far from perfect, but it's a beginning, you are welcome to try it out and send PRs improving the epub/pdf generation.

The root makefile should be the one in charge to make those PDF/EPUB files

Thanks!!

**Comment by XVilka** [comment]
I didn't remove gitbook *when* we did a fork. It has happened before because GitBook switched to the paid account, and we migrated to the mdBook: 
- https://github.com/radareorg/radare2book/commit/26215a96f9fbf023805769f9456fa81dd29759cd
- https://github.com/radareorg/radare2book/issues/301

**Comment by trufae** [comment]
I see. Ill just fix all those links and use mdbook/pandoc instead

**Comment by trufae** [comment]
everything is now done by the CI, updated artifacts will be published when the contents make sense. its currently quite a mess the way it's worded. but i'm focusing on fixing all this

**Comment by ildar** [comment]
this is so nice, thanks a lot!
