### ISSUE TITLE
dead link at https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2-book#301]
**Describe the issue**

the link to the miror here dead link at https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html is dead.

**How to reproduce?**

Check the link.

**Expected behavior**

**Possible fix**

Give a real link.

**Screenshots**

**Additional context**

**Comment by Heersin** [comment]
It seems that gitbook is not synchronized with this repo. Please visit this [link](https://book.rada.re/) for the latest version of radare2book.

As for the IOLI mirror, you can click https://github.com/radareorg/radare2book/raw/master/src/crackmes/ioli/IOLI-crackme.tar.gz to fetch it.

**Comment by XVilka** [comment]
GitBook is dead/deprecated and ideally Radare2 Book should be removed from it somehow, since it uses mdBook right now.
