### ISSUE TITLE
Build system: mdBook and Makefile

### ISSUE THREAD

**Issue by ratijas** [radareorg/radare2-book#304]
**Describe the issue**

Makefile is trash, npm modules fail not install, gitbook-cli (from package.json) is unmaintained/abandoned.

Currently this project uses GitHub actions exclusively, which in turn uses [rust-lang/mdBook](https://github.com/rust-lang/mdBook). So it shouldn't be an issue for deploying.

But local testing is broken; instructions are missing.

**How to reproduce?**

`git clone && make`

**Expected behavior**

Rendered book.

**Possible fix**

Provide alternative script and/or instructions to render the book locally.

AFAICT, installing `cargo install mdbook` should be just about enough of a setup. Alternatively, there's a docker image at [peaceiris/mdbook](https://hub.docker.com/r/peaceiris/mdbook).

**Screenshots**

None

**Additional context**

[Is this project abandoned?](https://github.com/GitbookIO/gitbook-cli/issues/99) -- GitbookIO/gitbook-cli

**Comment by ratijas** [comment]
Yep, running mdBook from the root of the book directory works.

**Comment by trufae** [comment]
I have added support for pandoc to generate pdf and epub, latest builds are in the release page. CI is still not ready and there's lot of unsync doc to be updated and reviewed. So just one little step forward to get that in shape
