### ISSUE TITLE
provide a tutorial with a common template to write plugins

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2-book#331]
## Description

*Please describe what are you missing or wanting to be improved*

In his current state radare2 allow any contributor to submit plugins. This is great. Everybody in the world can contribute in upstream. Sadly there is no template to write the body of plugins. This has as effect that each plugin is written in a very different style. Some have many many functions. some do not have so.

Then I suggest to write in the r2book some guidelines to write plugins as tutorial.

See https://github.com/radareorg/radare2/issues/19031

**Comment by trufae** [comment]
This is done in r2skel, also referenced from the book now
