### ISSUE TITLE
Render the book to info pages (and html too) and package it for distribution

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2-book#345]
So we can have tarballs that distros can package and compile

**Comment by trufae** [comment]
@prodrigestivill is this possible with pandoc or sthg?

**Comment by prodrigestivill** [comment]
Implemented in a PR the .info output.

For the HTML there are several ways depending on the intended use case.
Single HTML without images, with external images, needed to keep at the same space, or with embedded images inside the HTML...
